### ISSUE TITLE
ri_revo.mdl has flipped normals

### ISSUE THREAD

**Issue by Klausbdl** [laura-a-n-n/silent-hill-museum#1]
Born From A Wish/Item/ri_revo.mdl has flipped normals. Don't know if konami made it this way by default or if its your mistake.

**Comment by laura-a-n-n** [comment]
hi, thanks for the feedback!

this is known and appears to be intentional by konami. there are a few other models with flipped normals. they all seem to have the "r" prefix, e.g. Born From A Wish/mar/rlxx_mar.mdl has this.

also, rhhh_mar.mdl has this, but for that one i'm automatically turning on "back side" mode in the texture settings.

i'd like to do this for all models until i figure out more about this mystery, but for now you can put up a pull request to edit [the preferred params here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/src/objects/MuseumState.ts#L193) if you want to help!
