### ISSUE TITLE
No normal vector data?

### ISSUE THREAD

**Issue by Raq1** [laura-a-n-n/silent-hill-museum#2]
First of all, congratulations on this project. Before this there was barely any way to properly view/extract SH2 models, and this does the job perfectly.

I noticed that the tool is not importing normal data from the model (particuarly visible by looking at Maria's untextured shoulders, torso and hair). Or maybe there's no normal data at all in the .mdl files? Or maybe it is and something is going wrong when importing the .gltf file in a 3D software?

**Comment by laura-a-n-n** [comment]
hi, thank you!! actually, you may have just helped me realize i made a 1-line mistake XD there's some backstory:

you may have noticed there are up to two sections of each model: the "main"/primary geometry, and the "extra"/secondary geometry--these have toggles in the controls.

as far as i know, though, the "main" geometry in a mdl file does not store normal data in vertices. i am computing vertex normals automatically [here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/src/main.ts#L353) and [here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/src/main.ts#L386) for both "main" and "extra" geometry.

there _are_ 8 unknown bytes in every "main" vertex, but that wouldn't really leave room for three floats of normal data, and they seem to be integers of some kind. afaik map files do store this data, though.

however! the "extra" vertices (such as hair) do have some additional information attached, and i'm quite sure this _is_ normal data. it's defined [here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/ksy/mdl.ksy#L520) in the spec and i am attaching it to the model [here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/src/model.ts#L96).

but here's my mistake 💀: since the "extra"/secondary geometry _does_ have normal data, i shouldn't be computing it automatically. i'm likely overriding the normals by doing this. whoops! i'll put up a fix for this!

btw, i'm not totally sure that i know what you meant by this:

> particuarly visible by looking at Maria's untextured shoulders, torso and hair

could you give a filename where i could look at? please also see [this closed issue](https://github.com/laura-a-n-n/silent-hill-museum/issues/1).

also, please know that this project is still in v0, so not everything has been completely discovered.

thanks again!

**Comment by Raq1** [comment]
Thanks for the response! That would be interesting, actually, if the "main" meshes really have no normal data.

> particuarly visible by looking at Maria's untextured shoulders, torso and hair

Here's an image of what I meant by that:

![image](https://github.com/user-attachments/assets/01d0dc19-7867-410c-9ff7-b5b2587306a1)

This is **hhh_mar.mdl** converted to GLTF and imported in Blender. There's clear seams visible in her hair and shoulders, as a result of the normals being calculated automatically.

Also, I found this issue at the same time as the normals but didn't want to immediately open another issue about it (and maybe there's no need for it as I can just show it to you here), but it seems like the hair vertex weights also don't match?

![image](https://github.com/user-attachments/assets/971847d1-79f2-40ed-ba6d-2d90945207d6)

Her hair seems to move fine if only the first hair bone of each row of hair bones is moved/rotated. But if the second hair bone of each row is tweaked, the weights seem to be off. Hope it can be useful!

**Comment by laura-a-n-n** [comment]
this is great, i appreciate you looking into this! i'm sorry for the inconvenience.

because the hair and main geometry are rendered separately, seaming is much more likely. patching the mistake i mentioned above may help with this, but really:

> Her hair seems to move fine if only the first hair bone of each row of hair bones is moved/rotated. But if the second hair bone of each row is tweaked, the weights seem to be off

i definitely think this is also contributing to what's going on here. i haven't figured out how the bone weights in "extra" geometry work yet. tbh i'm just setting them to 1, 0, 0, 0 [here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/src/model.ts#L397), lmao. it's very likely the unknown floats [here](https://github.com/laura-a-n-n/silent-hill-museum/blob/main/ksy/mdl.ksy#L512). 

i'll take a look at it in a bit and try to have a patch up soon!

**Comment by Raq1** [comment]
Don't need to thank me, I appreciate **you** for doing all this! :D Glad this could help you!

**Comment by laura-a-n-n** [comment]
just put up the pull request, check it out!

**Comment by laura-a-n-n** [comment]
solved by #3
