### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by many-bees** [laura-a-n-n/silent-hill-museum#6]
On the devlog page it says to use the github issues page to get in contact with you so I just wanted to ask if you have any plans to eventually add the models from the other entries in the Silent Hill tetralogy. I wish I knew how to code so I could help out.

**Comment by laura-a-n-n** [comment]
hi, i do eventually want to! time permitting, the next game i'd like to do is silent hill 3 since that's my favorite in the series

this isn't what i'm working on at the moment though, it may be a while before i get there; right now i'm working an importer so you can swap out silent hill 2 models: https://github.com/laura-a-n-n/silent-hill-museum/pull/4#issuecomment-2277729392

**Comment by laura-a-n-n** [comment]
closing this, but welcome further discussion in thread.
